export default {
  name: "mainCategory",
  title: "Categoría principal",
  type: "document",
  fields: [
    {
      name: "titleEs",
      title: "Titulo español",
      type: "string",
    },
    {
      name: "titleEn",
      title: "Titulo inglés",
      type: "string",
    },
    {
      title: "Icon",
      name: "icon",
      type: "iconPicker",
      options: {
        outputFormat: "react",
        providers: ["fa"],
        filter: [
          "FaWineBottle",
          "FaUtensils",
          "FaIceCream",
          "FaGlassWhiskey",
          "FaGlassMartiniAlt",
          "FaAppleAlt",
          "FaCarrot",
          "FaCocktail",
          "FaCookieBite",
          "FaFish",
          "FaGlassCheers",
          "FaGlassMartini",
          "FaHamburger",
          "FaHotdog",
          "FaHeart",
          "FaLeaf",
          "FaLemon",
          "FaMortarPestle",
          "FaMugHot",
          "FaPepperHot",
          "FaPizzaSlice",
          "FaSeedling",
          "FaStar",
          "FaSun",
          "FaStopwatch",
          "FaTag",
          "FaThermometerFull",
          "FaThermometerEmpty",
          "FaTint",
          "FaUtensilSpoon",
          "FaWineGlassAlt",
          "FaWineGlass",
          "FaSnowflake",
          "FaUser",
          "FaDrumstickBite",
          "FaBeer",
        ],
      },
    },
  ],
};
